name = "mont"
description = "Read-First"
license = "MIT"
min_version = "0.16.1"
homepage = "https://github.com/kyoheiu/mont"
demo = "https://"

[extra]
# Author name, appears in footer.
mont_author = "author name"

# Path to the header favicon image.
# Save image to static/images.
mont_favicon = "/images/favicon.png"

mont_number = 10

[author]
homepage = "https://github.com/kyoheiu"
name = "Kyohei Uto"
